CREATE TABLE`universoleitura`.`ASSOSSIADOS`(
`CODID` INT NOT NULL, 
`RG`CHAR(7) NULL,
`NOME` VARCHAR(50) NULL,
`SOBRENOME` VARCHAR(50) NULL,
`ENDERECO` VARCHAR(150) NULL,
`CIDADE` VARCHAR(50) NULL,
`ESTADO` VARCHAR(50) NULL,
PRIMARY KEY (`CODID`)
);
ALTER TABLE `universoleitura`.`ASSOSSIADOS` RENAME TO `ASSOCIADOS`;

CREATE TABLE`universoleitura`.`EDITORAS`(
`CODIGO` INT NOT NULL, 
`RAZAO_SOCIAL` VARCHAR(150) NULL,
`TELEFONE` VARCHAR(100) NULL,
PRIMARY KEY (`CODIGO`)
);

CREATE TABLE`universoleitura`.`AUTORES`(
`CODIGO` INT NOT NULL, 
`SOBRENOME` VARCHAR(100) NULL,
`NOME` VARCHAR(100) NULL,
PRIMARY KEY (`CODIGO`)
);

CREATE TABLE`universoleitura`.`TELEFONES`(
`TELEFONEID` INT NOT NULL, 
`TELEFONE_SOCIO` VARCHAR(100) NULL,
`CODID` INT,
PRIMARY KEY (`TELEFONEID`),
CONSTRAINT `FKCODASSOC` FOREIGN KEY (`CODID`) REFERENCES `universoleitura`.`ASSOSSIADOS`(`CODID`)
);

CREATE TABLE `universoleitura`.`LIVROS`(
`COD_LIVROS` INT NOT NULL,
`COD_ISBN` VARCHAR(13),
`TITULO` VARCHAR(200),
`ANO_CRIACAO` DATE,
`COD_AUTORES` INT,
`ANO_PUBLICACAO` DATE,
`COD_EDITORAS` INT,
PRIMARY KEY (COD_LIVROS),
CONSTRAINT `FKCOD_AUTORES` FOREIGN KEY (`COD_AUTORES`) REFERENCES `universoleitura`.`AUTORES`(`CODIGO`),
CONSTRAINT `FKCOD_EDITORAS` FOREIGN KEY (`COD_EDITORAS`) REFERENCES `universoleitura`.`EDITORAS`(`CODIGO`)
);

CREATE TABLE `universoleitura`.`EXEMPLARES`(
`COD_EXEMPLARES` INT NOT NULL,
`COD_LIVRO` INT,
`SINISTRO` BOOL,
PRIMARY KEY (`COD_EXEMPLARES`),
CONSTRAINT `FKCOD_LIVRO` FOREIGN KEY (`COD_LIVRO`) REFERENCES `universoleitura`.`LIVROS`(`COD_LIVROS`)
);

CREATE TABLE `universoleitura`.`EPRESTIMOS`(
`COD_EMPRESTIMOS` INT NOT NULL,
`COD_ASSOC` INT,
`DATA` DATE,
`PRAZO_DEVOLUCAO` DATE,
`DATA_DEVOLUCAO` DATE,
PRIMARY KEY (`COD_EMPRESTIMOS`),
CONSTRAINT `FKASSOCIADOS` FOREIGN KEY (`COD_ASSOC`) REFERENCES `universoleitura`.`ASSOCIADOS`(`CODID`)
);
ALTER TABLE `universoleitura`.`EPRESTIMOS` RENAME TO `EMPRESTIMOS`;

CREATE TABLE `universoleitura`.`EPRESTIMOS_EXEMPLARES`(
`COD_EMPRE_EXEMPLA` INT NOT NULL,
`COD_ESPRESTIMO` INT,
`COD_EXEMPLARES` INT,
PRIMARY KEY (`COD_EMPRE_EXEMPLA`),
CONSTRAINT `FKEMPRESTIMO` FOREIGN KEY (`COD_ESPRESTIMO`) REFERENCES `universoleitura`.`EMPRESTIMOS`(`COD_EMPRESTIMOS`),
CONSTRAINT `FKEXEMPLARES` FOREIGN KEY (`COD_EXEMPLARES`) REFERENCES `universoleitura`.`EXEMPLARES`(`COD_EXEMPLARES`)
);